"""Add batches and training jobs tables

Revision ID: 2ddf82749ac2
Revises: 0003_add_model_registry
Create Date: 2025-12-17 12:34:54.476317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ddf82749ac2'
down_revision: Union[str, Sequence[str], None] = '0003_add_model_registry'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('outcomes_generated_at', sa.DateTime(), nullable=True),
    sa.Column('profile_count', sa.Integer(), nullable=True),
    sa.Column('label_count', sa.Integer(), nullable=True),
    sa.Column('default_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batch_status', 'batches', ['status'], unique=False)
    op.create_index(op.f('ix_batches_created_at'), 'batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_table('training_jobs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('training_data_count', sa.Integer(), nullable=True),
    sa.Column('new_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['new_version_id'], ['scorecard_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scorecard_version')
    op.add_column('scorecard_versions', sa.Column('version_number', sa.Integer(), nullable=True))
    op.add_column('scorecard_versions', sa.Column('auc_score', sa.Float(), nullable=True))
    op.add_column('scorecard_versions', sa.Column('training_data_count', sa.Integer(), nullable=True))
    op.add_column('scorecard_versions', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_scorecard_versions_version_number'), 'scorecard_versions', ['version_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scorecard_versions_version_number'), table_name='scorecard_versions')
    op.drop_column('scorecard_versions', 'archived_at')
    op.drop_column('scorecard_versions', 'training_data_count')
    op.drop_column('scorecard_versions', 'auc_score')
    op.drop_column('scorecard_versions', 'version_number')
    op.create_table('scorecard_version',
    sa.Column('version_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trained_on_batch_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parent_version_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('model_metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('coefficients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_version_id'], ['scorecard_version.version_id'], name=op.f('scorecard_version_parent_version_id_fkey')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('scorecard_version_pkey'))
    )
    op.drop_table('training_jobs')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_created_at'), table_name='batches')
    op.drop_index('idx_batch_status', table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
